Requisicao_RSS.WebUi/Controllers/GraficosController.cs
using Microsoft.AspNetCore.Mvc;
using Requisicao_RSS.Application.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Requisicao_RSS.WebUi.Controllers
{
    public class GraficosController : Controller
    {
        // Injeção de dependência
        private readonly IRequisicaoService _requisicaoService;

        public GraficosController(IRequisicaoService requisicaoService)
        {
            _requisicaoService = requisicaoService;
        }

        // Informações sobre a contagem das roupas
        public IActionResult Index()
        {

            ViewBag.QtdCalcaP = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCalca == "P").Count();
            ViewBag.QtdCalcaM = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCalca == "M").Count();
            ViewBag.QtdCalcaG = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCalca == "G").Count();
            ViewBag.QtdCalcaGG = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCalca == "GG").Count();
            ViewBag.QtdCalcaXG = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCalca == "XG").Count();


            ViewBag.QtdCamisaP = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCamisa == "P").Count();
            ViewBag.QtdCamisaM = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCamisa == "M").Count();
            ViewBag.QtdCamisaG = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCamisa == "G").Count();
            ViewBag.QtdCamisaGG = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCamisa == "GG").Count();
            ViewBag.QtdCamisaXG = _requisicaoService.GetRequisicoes().Result.Where(c => c.TamanhoCamisa == "XG").Count();

            return View();
        }
    }
}

Requisicao_RSS.WebUi/Controllers/RequisicoesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Requisicao_RSS.Application.DTOs;
using Requisicao_RSS.Application.Interfaces;
using Requisicao_RSS.WebUi.Models;
using System;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;


namespace Requisicao_RSS.WebUi.Controllers
{
    public class RequisicoesController : Controller
    {
        // Injeção de dependência
        private readonly IRequisicaoService _requisicaoService;
        private readonly IFuncionarioService _funcionarioService;

        public RequisicoesController(IRequisicaoService requisicaoService, IFuncionarioService funcionarioService)
        {
            _requisicaoService = requisicaoService;
            _funcionarioService = funcionarioService;

        }

        // Home
        [HttpGet]
        public async Task<IActionResult> Index(int pagina = 1)
        {
            // Lista de requisições
            var xRequisicoes = await _requisicaoService.GetRequisicoes();

            // paginando os dados recebidos
            IPagedList<RequisicaoDTO> xRequisicoesPaginadas = xRequisicoes.ToPagedList(pagina, 10);

            return View(xRequisicoesPaginadas);
        }


        // View Details ( Detalhes da requisição )
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var xRequisicao = await _requisicaoService.GetById(id);

            ViewBag.FuncionarioNome = _funcionarioService.GetById(xRequisicao.FuncionarioId).Result.Nome;

            return View(xRequisicao);
        }

        // Pesquisa para filtrar uma requisição por data específica
        [HttpPost]
        public ActionResult GetDataRequisicao(DateTime data, int pagina = 1)
        {
            var xRequisicoes = _requisicaoService.GetRequisicoes().Result.Where(r => r.Data == data).ToList();

            if (xRequisicoes.Count == 0)
            {
                var allRequisicoes = _requisicaoService.GetRequisicoes();
                TempData["error"] = "Data não localizada.";
                return RedirectToAction("Index", allRequisicoes);
            }

            IPagedList<RequisicaoDTO> allRequisicoesPaginadas = xRequisicoes.ToPagedList(pagina, 1000000);

            ViewBag.xCondition = 1;

            return View("Index", allRequisicoesPaginadas);
        }


        // Add requisição
        [HttpGet]
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
                return RedirectToAction(nameof(Index));

            // Localizando funcionário
            var xFuncionario = await _funcionarioService.GetById(id);

            // Gera tamanho personalizado "Não trocou"
            var myTamanhos = new Tamanhos().GetTamanhos();
            myTamanhos.Add(new Tamanhos { Valor = "Não Trocou", Texto = "Não Trocou" });

            //Capturando todas as informações sobre o funcionario
            ViewBag.Registro = xFuncionario.Registro;
            ViewBag.FuncionarioId = xFuncionario.FuncionarioId;
            ViewBag.FuncionarioNome = xFuncionario.Nome;
            ViewBag.FuncionarioFuncao = xFuncionario.Funcao;
            ViewBag.TamanhosCamisa = new SelectList(myTamanhos, "Valor", "Texto", xFuncionario.BaseCamisa);
            ViewBag.TamanhosCalca = new SelectList(myTamanhos, "Valor", "Texto", xFuncionario.BaseCalca);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RequisicaoDTO requisicao)
        {
            if (ModelState.IsValid)
            {
                // Verifica se já existe uma requisição para o funcionário na mesma data
                var xFuncionario = _requisicaoService.GetRequisicoes().Result.Where(r => r.Data == requisicao.Data).Where(r => r.Registro == requisicao.Registro).Count();

                if (xFuncionario > 0)
                {
                    TempData["error"] = "Funcionário já possui requisição.";
                }
                else
                {
                    await _requisicaoService.Add(requisicao);
                    TempData["success"] = "Requisição cadastrada com sucesso.";
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                TempData["error"] = "Erro ao cadastrar a requisição.";
            }

            // Gera tamanho personalizado "Não trocou" novamente
            var myTamanhos = new Tamanhos().GetTamanhos();
            myTamanhos.Add(new Tamanhos { Valor = "Não Trocou", Texto = "Não Trocou" });

            // Manda novamente as informações do funcionário
            ViewBag.Registro = requisicao.Registro;
            ViewBag.FuncionarioId = requisicao.FuncionarioId;
            ViewBag.TamanhosCamisa = new SelectList(myTamanhos, "Valor", "Texto", requisicao.TamanhoCalca);
            ViewBag.TamanhosCalca = new SelectList(myTamanhos, "Valor", "Texto", requisicao.TamanhoCamisa);
            ViewBag.FuncionarioFuncao = _funcionarioService.GetById(requisicao.FuncionarioId).Result.Funcao;
            ViewBag.FuncionarioNome = _funcionarioService.GetById(requisicao.FuncionarioId).Result.Nome;

            return View(requisicao);
        }

        // Edit uma requisição
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                TempData["error"] = "Erro ao localizar a requisição.";
            }

            // Capturando requisicao
            var xRequisicao = await _requisicaoService.GetById(id);

            // Capturando informações sobre o funcionário
            ViewBag.FuncionarioRegistro = _funcionarioService.GetById(xRequisicao.FuncionarioId).Result.Registro;
            ViewBag.FuncionarioFuncao = _funcionarioService.GetById(xRequisicao.FuncionarioId).Result.Funcao;

            if (xRequisicao == null)
            {
                TempData["error"] = "Erro ao localizar a requisição.";
            }

            // Gera tamanho personalizado "Não trocou"
            var myTamanhos = new Tamanhos().GetTamanhos();

            myTamanhos.Add(new Tamanhos { Valor = "Não Trocou", Texto = "Não Trocou" });

            ViewBag.TamanhosCamisa = new SelectList(myTamanhos, "Valor", "Texto", xRequisicao.TamanhoCamisa);
            ViewBag.TamanhosCalca = new SelectList(myTamanhos, "Valor", "Texto", xRequisicao.TamanhoCalca);

            return View(xRequisicao);
        }


        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> Edit(RequisicaoDTO requisicao)
        {
            var myTamanhos = new Tamanhos().GetTamanhos();

            if (ModelState.IsValid)
            {
                await _requisicaoService.Update(requisicao);
                TempData["success"] = "Requisição editada com sucesso.";
                return RedirectToAction("Index", "Funcionarios");
            }
           
                TempData["error"] = "Erro ao editar a requisição.";
           

            return RedirectToAction("Index", "Funcionarios");
        }

        // Remove uma requisição

        [HttpGet]
        public async Task<IActionResult> Remove(int? id)
        {
            if (id == null)
                TempData["error"] = "Erro ao localizar a requisição.";

            var xRequisicao = await _requisicaoService.GetById(id);

            ViewBag.NomeFuncionario = _funcionarioService.GetById(xRequisicao.FuncionarioId).Result.Nome;

            if (xRequisicao == null)
                TempData["error"] = "Erro ao localizar a requisição.";

            return View(xRequisicao);
        }

        [HttpPost(), ActionName("Remove")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _requisicaoService.Remove(id);
            TempData["success"] = "Requisição removida com sucesso.";
            return RedirectToAction("Index");
        }
    }
}

Requisicao_RSS.WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Requisições RSS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/toastr.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="~/css/site.css" />

    
</head>
<body style="background-color: #F0F0F0; ">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow mb-3 border" style="box-shadow: 0px 12px 12px -11px rgba(0,0,0,0.42); ">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1 d-flex justify-content-around">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requisicoes" asp-action="Index">Requisicões</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedores" asp-action="Index">Fornecedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Graficos" asp-action="Index">Gráficos</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
            <input type="hidden" id="success"
                   value="@TempData["success"]" />
            <input type="hidden" id="info"
                   value="@TempData["info"]" />
            <input type="hidden" id="warning"
                   value="@TempData["warning"]" />
            <input type="hidden" id="error"
                   value="@TempData["error"]" />


        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/jquery.mask.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>


    <script>
        $(function () {
            var displayMessage = function (message, msgType) {
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": true,
                    "positionClass": "toast-top-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "500",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                };
                toastr[msgType](message);
            };

            if ($('#success').val()) {
                displayMessage($('#success').val(), 'success');
            }
            if ($('#info').val()) {
                displayMessage($('#info').val(), 'info');
            }
            if ($('#warning').val()) {
                displayMessage($('#warning').val(), 'warning');
            }
            if ($('#error').val()) {
                displayMessage($('#error').val(), 'error');
            }
        });


        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>