Requisicao_RSS.WebUi/Controllers/FornecedoresController.cs
using Microsoft.AspNetCore.Mvc;
using Requisicao_RSS.Application.DTOs;
using Requisicao_RSS.Application.Interfaces;
using Rotativa.AspNetCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace Requisicao_RSS.WebUi.Controllers
{
    public class FornecedoresController : Controller
    {
        // Injeção de dependência
        private readonly IFornecedorService _fornecedorService;
        private readonly IEntregaMaterialService _entregaMaterialService;
        private readonly IRetiradaMaterialService _retiradaMaterialService;

        public FornecedoresController(IFornecedorService fornecedorService, IEntregaMaterialService entregaMaterialService, IRetiradaMaterialService retiradaMaterialService)
        {
            _fornecedorService = fornecedorService;
            _entregaMaterialService = entregaMaterialService;
            _retiradaMaterialService = retiradaMaterialService;
        }

        // Get fornecedores
        [HttpGet]
        public async Task<IActionResult> Index(int pagina = 1)
        {
            var xFornecedores = await _fornecedorService.GetFornecedores();

            IPagedList<FornecedorDTO> AllFornec = xFornecedores.ToPagedList(pagina, 10);

            return View(AllFornec);
        }


        // Menu de opções para o fornecedor
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var xFornecedor = await _fornecedorService.GetById(id);

            ViewBag.FornId = id;
            ViewBag.NomeFornecedor = _fornecedorService.GetById(id).Result.Nome;

            return View(xFornecedor);
        }


        // Get entregas fornecedor específico
        public async Task<IActionResult> ListaEntregas(int? id, int pagina = 1)
        {
            var xEntregas = await _entregaMaterialService.GetEntregasMateriais();
            var detalhes = xEntregas.Where(x => x.FornecedorId == id);


            ViewBag.NomeFornecedor = _fornecedorService.GetById(id).Result.Nome;
            ViewBag.FornecedorId = id;

            IPagedList<EntregaMaterialDTO> aLLeEntreg = detalhes.ToPagedList(pagina, 10);

            return View(aLLeEntreg);
        }


        // Campo de pesquisa para filtrar uma entrega por data específica
        [HttpPost]
        public ActionResult GetDataEntrega(DateTime data, int fornecedorId, int pagina = 1)
        {
            var xEntregas = _entregaMaterialService.GetEntregasMateriais().Result.Where(r => r.Data == data).Where(r => r.FornecedorId == fornecedorId).ToList();

            if (xEntregas.Count == 0)
            {
                TempData["error"] = "Data não localizada.";
                var allEntregas = _entregaMaterialService.GetEntregasMateriais().Result.Where(r => r.FornecedorId == fornecedorId).ToList();


                ViewBag.FornecedorId = fornecedorId;
                ViewBag.NomeFornecedor = _fornecedorService.GetById(fornecedorId).Result.Nome;

                IPagedList<EntregaMaterialDTO> allEntregasPaginadas = allEntregas.ToPagedList(pagina, 10);

                return View("ListaEntregas", allEntregasPaginadas);
            }

            ViewBag.xCondition = 1;

            ViewBag.FornecedorId = fornecedorId;

            ViewBag.NomeFornecedor = _fornecedorService.GetById(fornecedorId).Result.Nome;

            IPagedList<EntregaMaterialDTO> entregasPaginadas = xEntregas.ToPagedList();

            return View("ListaEntregas", entregasPaginadas);
        }

        // Página de pesquisa de entregas de materiais por data de inicio e data fim para relatório em PDF
        public IActionResult RelatorioEntregas(int id)
        {
            ViewBag.FornecedorId = id;
            return View();
        }

        // Gerar Relatorio de entregas em PDF
        public IActionResult RelatorioEntregasPDF(int id, DateTime dataInicio, DateTime dataFim)
        {
            // Tentar fazer chegar a data correta

            ViewData["DataInicio"] = dataInicio.ToShortDateString();
            ViewData["DataFim"] = dataFim.ToShortDateString();
            ViewData["NomeFornecedor"] = _fornecedorService.GetById(id).Result.Nome.ToString();

            var xEntregas = _entregaMaterialService.GetEntregasMateriais().Result.Where(x => x.FornecedorId == id).Where(x => x.Data >= dataInicio).Where(x => x.Data <= dataFim).ToList();

            var xFornecedorNome = _fornecedorService.GetById(id).Result.Nome;

            return new ViewAsPdf(xEntregas, viewData: ViewData)
            {
                IsGrayScale = false,
                PageSize = Rotativa.AspNetCore.Options.Size.A4,
                PageMargins = new Rotativa.AspNetCore.Options.Margins(0, 10, 0, 10),

            };
        }


        // Get retiradas fornecedor específico
        public async Task<IActionResult> ListaRetiradas(int? id, int pagina = 1)
        {
            var xRetiradas = await _retiradaMaterialService.GetRetiradasMateriais();
            var detalhes = xRetiradas.Where(x => x.FornecedorId == id);


            ViewBag.NomeFornecedor = _fornecedorService.GetById(id).Result.Nome;

            ViewBag.FornecedorId = id;

            IPagedList<RetiradaMaterialDTO> allRetiradas = detalhes.ToPagedList(pagina, 10);

            return View(allRetiradas);
        }


        // Campo de pesquisa para filtrar uma retirada por data específica
        [HttpPost]
        public ActionResult GetDataRetirada(DateTime data, int fornecedorId, int pagina = 1)
        {
            var xRetiradas = _retiradaMaterialService.GetRetiradasMateriais().Result.Where(r => r.Data == data).Where(r => r.FornecedorId == fornecedorId).ToList();

            if (xRetiradas.Count == 0)
            {
                TempData["error"] = "Data não localizada.";
                var allRetiradas = _retiradaMaterialService.GetRetiradasMateriais().Result.Where(r => r.FornecedorId == fornecedorId).ToList();


                ViewBag.FornecedorId = fornecedorId;
                ViewBag.NomeFornecedor = _fornecedorService.GetById(fornecedorId).Result.Nome;

                IPagedList<RetiradaMaterialDTO> allRetiradasPaginadas = allRetiradas.ToPagedList(pagina, 10);

                return View("ListaRetiradas", allRetiradasPaginadas);
            }

            ViewBag.xCondition = 1;

            ViewBag.FornecedorId = fornecedorId;

            ViewBag.NomeFornecedor = _fornecedorService.GetById(fornecedorId).Result.Nome;

            IPagedList<RetiradaMaterialDTO> retiradasPaginadas = xRetiradas.ToPagedList();

            return View("ListaRetiradas", retiradasPaginadas);
        }


        // Página de pesquisa de retirada de materiais por data de inicio e data fim para relatório em PDF
        public IActionResult RelatorioRetiradas(int id)
        {
            ViewBag.FornecedorId = id;
            return View();
        }

        // Gerar Relatorio de entregas em PDF
        public IActionResult RelatorioRetiradasPDF(int id, DateTime dataInicio, DateTime dataFim)
        {
            // Tentar fazer chegar a data correta

            ViewData["DataInicio"] = dataInicio.ToShortDateString();
            ViewData["DataFim"] = dataFim.ToShortDateString();
            ViewData["NomeFornecedor"] = _fornecedorService.GetById(id).Result.Nome.ToString();

            var xEntregas = _retiradaMaterialService.GetRetiradasMateriais().Result.Where(x => x.FornecedorId == id).Where(x => x.Data >= dataInicio).Where(x => x.Data <= dataFim).ToList();

            var xFornecedorNome = _fornecedorService.GetById(id).Result.Nome;

            return new ViewAsPdf(xEntregas, viewData: ViewData)
            {
                IsGrayScale = true,
                PageSize = Rotativa.AspNetCore.Options.Size.A4,
                PageMargins = new Rotativa.AspNetCore.Options.Margins(0, 10, 0, 10),

            };
        }




        // Add fornecedor
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(FornecedorDTO fornecedorDTO)
        {
            if (ModelState.IsValid)
            {
                await _fornecedorService.Add(fornecedorDTO);
                TempData["success"] = "Fornecedor Cadastrado com sucesso.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Erro ao cadastrar o fornecedor.";
            }

            return View();
        }

        // Edit fornecedor
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var xFornecedor = await _fornecedorService.GetById(id);

            if (xFornecedor == null)
                return NotFound();

            return View(xFornecedor);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(FornecedorDTO fornecedorDTO)
        {
            if (ModelState.IsValid)
            {
                await _fornecedorService.Update(fornecedorDTO);
                TempData["success"] = "Fornecedor editado com sucesso.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Erro ao editar o fornecedor.";
            }

            return View(fornecedorDTO);
        }

        // Remove fornecedor
        [HttpGet]
        public async Task<IActionResult> Remove(int? id)
        {
            if (id == null)
                TempData["error"] = "Erro ao localizar o fornecedor";

            var xFornecedor = await _fornecedorService.GetById(id);

            if (xFornecedor == null)
                TempData["error"] = "Erro ao localizar o fornecedor";

            return View(xFornecedor);
        }

        [HttpPost(), ActionName("Remove")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

Requisicao_RSS.WebUi/Views/EntregaMateriais/Create.cshtml
<!-- import model -->
@model Requisicao_RSS.Application.DTOs.EntregaMaterialDTO

    <!-- start header -->
    <div class="row">
        <div class="col-12 text-center mt-3 mb-3">
            <h4 style="font-weight: 200">Cadastrar Entrega de Material <br /> <strong>@ViewBag.FornecedorNome</strong></h4>
        </div>
    </div>

    <!-- formulario cadastro de materiais-->
    <form asp-action="Create" method="POST" style="width:70%;margin:0 auto;" class="form-responsive">
        <hr />

        <input type="hidden" asp-for="FornecedorId" class="form-control" value="@ViewBag.FornecedorId" />

        <!-- exibe lista de erros de validações do formulário -->
        <div asp-validation-summary="All" class="text-danger"></div>

        <!-- nome do material -->
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <label asp-for="NomeFornecedor">Nome</label>
                    <input asp-for="NomeFornecedor" type="text" class="form-control text-center" value="@ViewBag.FornecedorNome" readonly style="font-weight:700;" />
                </div>
            </div>
        </div>

        <!-- data da entrega-->
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Data">Data</label>
                    <input asp-for="Data" type="date" class="form-control data" id="data" />
                </div>
                <div class=" col-md-6">
                    <label asp-for="Tipo">Tipo de material entregue</label>
                    <select class="form-control" asp-for="Tipo" id="SelectTipo">
                        <option value="">Selecione</option>
                        <option>Uniforme</option>
                        <option>Luva</option>
                    </select>
                </div>
            </div>
        </div>

        <!--  quantidade de camisas -->
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">
                    <label asp-for="QuantidadeCamisas">Quantidade de Camisas</label>
                    <input type="number" asp-for="QuantidadeCamisas" class="form-control" id="txtQtdCamisas" />
                </div>
                <div class="col-md-4">
                    <label asp-for="QuantidadeCalcas">Quantidade de Calças</label>
                    <input type="number" asp-for="QuantidadeCalcas" class="form-control" id="txtQtdCalcas" />
                </div>
                <div class="col-md-4">
                    <label asp-for="QuantidadeLuvas">Quantidade de Luvas</label>
                    <input type="number" asp-for="QuantidadeLuvas" class="form-control" id="txtQtdLuvas" />
                </div>
            </div>
        </div>

        <!-- divergências -->
        <div class="form-group">
            <div class="row">
                <div class="col-12 col-md-4">
                    <label asp-for="Divergencia">Houve Divergência?</label>
                    <select class="form-control mt-2" asp-for="Divergencia" id="SelectDivergencia">
                        <option value="">Selecione</option>
                        <option>Sim</option>
                        <option>Não</option>
                    </select>
                </div>
                <div class="col-md-8">
                    <label asp-for="Observacoes">Observações</label>
                    <textarea style="resize: none;" id="txtObservacoes" class="form-control" TextMode="MultiLine" placeholder="Escreva aqui..." asp-for="Observacoes"></textarea>
                </div>
            </div>
        </div>

        <!-- submmit form -->
        <div class="form-group">
            <div class="row mt-4">
                <div class="col-12">
                    <div class="d-flex">
                        <button type="submit" class="btn btn-primary d-flex align-items-center btn-acoes btn-add">
                            <span class="mr-1">Cadastrar</span>
                            <i class="material-icons" style="font-size:15px;color:white;">add</i>
                        </button>
                        <div class="btn btn-danger d-flex btn-acoes ml-3">
                            <a style="color:#fff;" asp-controller="Fornecedores" asp-action="Details" asp-route-id="@ViewBag.FornecedorId"><span class="mr-1">Cancelar</span></a>
                            <i class="material-icons" style="font-size:15px;color:white;">clear</i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>


    <!-- scripts -->
    @section Scripts {
        <script>

            $('#SelectTipo').change(function () {
                if ($(this).val() == 'Uniforme') {
                    $("#txtQtdLuvas").val(0);
                    $("#txtQtdCamisas").val('');
                    $("#txtQtdCalcas").val('');
                    $("#txtQtdCalcas").prop('readonly', false);
                    $("#txtQtdCamisas").prop('readonly', false);

                    $("#txtQtdLuvas").prop('readonly', true);
                    $("#txtQtdCamisas").focus();


                } else if ($(this).val() == 'Luva') {
                    $("#txtQtdLuvas").prop('readonly', false);
                    $("#txtQtdLuvas").val('');
                    $("#txtQtdLuvas").focus();
                    $("#txtQtdCamisas").val(0)
                    $("#txtQtdCalcas").val(0);
                    $("#txtQtdCamisas").prop('readonly', true);
                    $("#txtQtdCalcas").prop('readonly', true);
                    $("#txtQtdLuvas").focus();
                };
            });

            $(document).ready(function () {



                $("#txtObservacoes").prop('readonly', true);

                $("#SelectDivergencia").change(function () {
                    if ($(this).val() == 'Sim') {
                        $("#txtObservacoes").prop('readonly', false);
                    } else if ($(this).val() == 'Não') {
                        $("#txtObservacoes").prop('readonly', true);
                    } else if ($(this).val() == '') {
                        $("#txtObservacoes").prop('readonly', true);
                    };
                })
            });

        </script>
    };

Requisicao_RSS.WebUi/Views/EntregaMateriais/Details.cshtml
<!-- import model -->
@model Requisicao_RSS.Application.DTOs.EntregaMaterialDTO

    <!-- header -->
    <div class="row">
        <div class="col-12 mt-3 mb-2">
            <h3 style="font-weight: 100;">Detalhes da Entrega</h3>
        </div>
        <div class="col-3 col-md-1 mb-4">
            <a asp-controller="Fornecedores" asp-action="ListaEntregas" asp-route-id="@Model.FornecedorId" class="d-flex align-items-center justify-content-center btn btn-primary btn-sm "><i class="material-icons" style="font-size:15px;color:#fff;">arrow_back_ios</i>Voltar</a>
        </div>
    </div>

    <!-- Conteúdo -->
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                <li class="list-group-item"><strong>Data da entrega: </strong>@Html.DisplayFor(c => c.Data)</li>
                <li class="list-group-item"><strong>Nome: </strong> @Model.NomeFornecedor</li>
                <li class="list-group-item"><strong>Tipo de entrega: </strong> @Model.Tipo</li>

                @if (Model.Tipo.ToString().ToLower() == "luva")
                {
                    <li class="list-group-item"><strong>Quantidade Luvas: </strong> @Model.QuantidadeLuvas</li>
                }
                @if (Model.Tipo.ToString().ToLower() == "uniforme")
                {
                    <li class="list-group-item"><strong>Quantidade Camisas: </strong> @Model.QuantidadeCamisas</li>
                    <li class="list-group-item"><strong>Quantidade Calças: </strong> @Model.QuantidadeCalcas</li>
                }

                <li class="list-group-item"><strong>Houve divergência?: </strong> @Model.Divergencia</li>

                @if (Model.Divergencia.ToString().ToLower() == "sim")
                {
                    <li class="list-group-item text-danger"><strong>Observações: </strong> @Model.Observacoes</li>
                }
            </ul>
        </div>
    </div>

Requisicao_RSS.WebUi/Views/EntregaMateriais/Edit.cshtml
<!-- import model -->
@model Requisicao_RSS.Application.DTOs.EntregaMaterialDTO

    <!-- header -->
    <div class="row">
        <div class="col-12 text-center mt-3 mb-3">
            <h4 style="font-weight: 200">Editar Entrega de Material <br /> <strong>@Model.NomeFornecedor</strong></h4>
        </div>
    </div>

    <!-- form de edição de entrega de materiais-->
    <form asp-action="Edit" method="POST" style="width:70%; margin: 0 auto;">

        <hr />

        <!-- passando o id do fornecedor e da entrega -->
        <input type="hidden" asp-for="FornecedorId" class="form-control" value="@Model.FornecedorId" />
        <input type="hidden" asp-for="EntregaMaterialId" class="form-control" value="@Model.EntregaMaterialId" />

        <!-- exibe lista de erros de validações do formulário -->
        <div asp-validation-summary="All" class="text-danger"></div>

        <!-- nome do material -->
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <label asp-for="NomeFornecedor">Nome</label>
                    <input asp-for="NomeFornecedor" type="text" class="form-control text-center" value="@Model.NomeFornecedor" readonly />
                </div>
            </div>
        </div>

        <!-- data da entrega-->
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Data">Data</label>
                    <input asp-for="Data" type="date" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label asp-for="Tipo">Tipo de material entregue</label>
                    <select class="form-control" asp-for="Tipo" id="SelectTipo">
                        <option value="">Selecione</option>
                        <option>Uniforme</option>
                        <option>Luva</option>
                    </select>
                </div>
            </div>
        </div>

        <!--  quantidade de camisas -->
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">
                    <label asp-for="QuantidadeCamisas">Quantidade de Camisas</label>
                    <input type="number" asp-for="QuantidadeCamisas" class="form-control" id="txtQtdCamisas" />
                </div>
                <div class="col-md-4">
                    <label asp-for="QuantidadeCalcas">Quantidade de Calças</label>
                    <input type="number" asp-for="QuantidadeCalcas" class="form-control" id="txtQtdCalcas" />
                </div>
                <div class="col-md-4">
                    <label asp-for="QuantidadeLuvas">Quantidade de Luvas</label>
                    <input type="number" asp-for="QuantidadeLuvas" class="form-control" id="txtQtdLuvas" />
                </div>
            </div>
        </div>

        <!-- divergências -->
        <div class="form-group">
            <div class="row">
                <div class="col-4">
                    <label asp-for="Divergencia">Houve Divergência?</label>
                    <select class="form-control mt-2" asp-for="Divergencia" id="SelectDivergencia">
                        <option value="">Selecione</option>
                        <option>Sim</option>
                        <option>Não</option>
                    </select>
                </div>
                <div class="col-md-8">
                    <label asp-for="Observacoes">Observações</label>
                    <textarea style="resize: none;" id="txtObservacoes" class="form-control" TextMode="MultiLine" placeholder="Escreva aqui..." asp-for="Observacoes"></textarea>
                </div>
            </div>
        </div>

        <!-- submmit form -->
        <div class="form-group">
            <div class="row mt-4">
                <div class="col-12">
                    <div class="d-flex">
                        <button type="submit" class="btn btn-primary d-flex btn-acoes btn-add">
                            <span class="mr-1">Editar</span>
                            <i class="material-icons" style="font-size:15px;color:white;">edit</i>
                        </button>
                        <div class="btn btn-danger d-flex btn-acoes ml-3">
                            <a style="color:#fff;"  asp-controller="Fornecedores" asp-action="ListaEntregas" asp-route-id="@Model.FornecedorId"><span class="mr-1">Cancelar</span></a>
                            <i class="material-icons" style="font-size:15px;color:white;">clear</i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>


    <!-- scripts -->
    @section Scripts {
        <script>

            $('#SelectTipo').change(function () {
                if ($(this).val() == 'Uniforme') {
                    $("#txtQtdLuvas").val(0);
                    $("#txtQtdCamisas").val('');
                    $("#txtQtdCalcas").val('');
                    $("#txtQtdCalcas").prop('readonly', false);
                    $("#txtQtdCamisas").prop('readonly', false);

                    $("#txtQtdLuvas").prop('readonly', true);
                    $("#txtQtdCamisas").focus();


                } else if ($(this).val() == 'Luva') {
                    $("#txtQtdLuvas").prop('readonly', false);
                    $("#txtQtdLuvas").val('');
                    $("#txtQtdLuvas").focus();
                    $("#txtQtdCamisas").val(0);
                    $("#txtQtdCalcas").val(0);
                    $("#txtQtdCamisas").prop('readonly', true);
                    $("#txtQtdCalcas").prop('readonly', true);
                    $("#txtQtdLuvas").focus();
                };
            });

            $(document).ready(function () {



                if ($("#SelectDivergencia").val() == 'Sim') {
                    $("#txtObservacoes").prop('readonly', false);
                } else {
                    $("#txtObservacoes").prop('readonly', true);
                }

                $("#SelectDivergencia").change(function () {
                    if ($(this).val() == 'Sim') {
                        $("#txtObservacoes").prop('readonly', false);
                    } else if ($(this).val() == 'Não') {
                        $("#txtObservacoes").prop('readonly', true);
                    } else if ($(this).val() == '') {
                        $("#txtObservacoes").prop('readonly', true);
                    };
                })
            });

        </script>
    };

Requisicao_RSS.WebUi/Views/EntregaMateriais/RelatorioEntregas.cshtml
<div class="row">
    <div class="col mt-5 mb-5 ml-5 text-center">
        <h2 style="font-weight:lighter">Relatório de Entregas de Materiais</h2>
        <hr style="width:30%;" />
    </div>
</div>


<div class="row">
    <div class="col-6" style="margin: 0 auto;">
        <form asp-action="VisualizarComoPDF" id="formData" name="formData" class="form-horizontal" target="_blank">
            <input type="hidden" value="@ViewBag.FuncId" name="id" id="id" />
            <div class="form-group">
                <label for="dataInicio" class="col-sm-2 control-label">Data Inicio:</label>
                <input type="date" class="form-control" id="dataInicio" name="dataInicio" required data-toggle="tooltip" data-placement="left" title="Data inical">
            </div>
            <div class="form-group">
                <label for="dataFim" class="col-sm-2 control-label">Data Fim</label>
                <input type="date" class="form-control" id="dataFim" name="dataFim" required data-toggle="tooltip" data-placement="left" title="Data final">
            </div>
            <div>

                <span>@Html.ActionLink("Gerar Relatório","VisualizarComoPDF", "Fornecedores", null, new { target = "_blank" })</span> <a class="btn btn-danger" asp-controller="EntregaMateriais" asp-action="Details" asp-route-id="@ViewBag.FornecedorId">&nbsp;Voltar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {

    <script>
        $(document).ready(function () {
            $('#formData').on('submit', function () {
                alert('You submitted the form!');
            });
        });
    </script>    

}

Requisicao_RSS.WebUi/Views/EntregaMateriais/Remove.cshtml
<!-- Import model-->
@model Requisicao_RSS.Application.DTOs.EntregaMaterialDTO
<!-- Header -->
<div class="row">
    <div class="col-12 mt-3 mb-3">
        <h2 class="text-danger" style="font-weight: 200">Deseja realmente remover?</h2>
    </div>
</div>

<!-- Informações da entrega -->
<div class="row">
    <div class="col-12">
        <strong>Tipo: </strong> @Model.Tipo
    </div>
    <div class="col-12">
        <strong>Data: </strong> @Html.DisplayFor(c => c.Data)
    </div>
</div>

<hr />

<!-- Ações -->
<div class="row">
    <div class="col-12">
        <form asp-action="Remove">
            <!-- Id fornecedor-->
            <input type="hidden" asp-for="EntregaMaterialId" />
            <input type="hidden" asp-for="FornecedorId" name="fornecedorId">

            <div class="form-group d-flex justify-content-start">
                <!-- Remover -->
                <button type="submit" class="btn btn-danger d-flex align-items-center justify-content-around p-l-3  btn-acoes">
                    <span class="mr-2">Remover</span>
                    <i class="material-icons" style="font-size:16px;margin-top:3px;color:white;font-weight:600;">delete</i>
                </button>

                &nbsp;&nbsp;

                <!-- Cancelar -->
                <div class="btn btn-dark d-flex align-items-center btn-acoes">
                    <a style="color:#fff;" asp-controller="Fornecedores" asp-action="ListaEntregas" asp-route-id="@Model.FornecedorId"><span class="mr-1">Cancelar</span></a>
                    <i class="material-icons" style="font-size:16px;margin-top:3px;color:white;font-weight:600;">clear</i>
                </div>
            </div>
        </form>
    </div>
</div>