Requisicao_RSS.WebUi/Controllers/FornecedoresController.cs
using Microsoft.AspNetCore.Mvc;
using Requisicao_RSS.Application.DTOs;
using Requisicao_RSS.Application.Interfaces;
using Rotativa.AspNetCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace Requisicao_RSS.WebUi.Controllers
{
    public class FornecedoresController : Controller
    {
        // Injeção de dependência
        private readonly IFornecedorService _fornecedorService;
        private readonly IEntregaMaterialService _entregaMaterialService;
        private readonly IRetiradaMaterialService _retiradaMaterialService;

        public FornecedoresController(IFornecedorService fornecedorService, IEntregaMaterialService entregaMaterialService, IRetiradaMaterialService retiradaMaterialService)
        {
            _fornecedorService = fornecedorService;
            _entregaMaterialService = entregaMaterialService;
            _retiradaMaterialService = retiradaMaterialService;
        }

        // Get fornecedores
        [HttpGet]
        public async Task<IActionResult> Index(int pagina = 1)
        {
            var xFornecedores = await _fornecedorService.GetFornecedores();

            IPagedList<FornecedorDTO> AllFornec = xFornecedores.ToPagedList(pagina, 10);

            return View(AllFornec);
        }


        // Menu de opções para o fornecedor
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var xFornecedor = await _fornecedorService.GetById(id);

            ViewBag.FornId = id;
            ViewBag.NomeFornecedor = _fornecedorService.GetById(id).Result.Nome;

            return View(xFornecedor);
        }


        // Get entregas fornecedor específico
        public async Task<IActionResult> ListaEntregas(int? id, int pagina = 1)
        {
            var xEntregas = await _entregaMaterialService.GetEntregasMateriais();
            var detalhes = xEntregas.Where(x => x.FornecedorId == id);


            ViewBag.NomeFornecedor = _fornecedorService.GetById(id).Result.Nome;
            ViewBag.FornecedorId = id;

            IPagedList<EntregaMaterialDTO> aLLeEntreg = detalhes.ToPagedList(pagina, 10);

            return View(aLLeEntreg);
        }


        // Campo de pesquisa para filtrar uma entrega por data específica
        [HttpPost]
        public ActionResult GetDataEntrega(DateTime data, int fornecedorId, int pagina = 1)
        {
            var xEntregas = _entregaMaterialService.GetEntregasMateriais().Result.Where(r => r.Data == data).Where(r => r.FornecedorId == fornecedorId).ToList();

            if (xEntregas.Count == 0)
            {
                TempData["error"] = "Data não localizada.";
                var allEntregas = _entregaMaterialService.GetEntregasMateriais().Result.Where(r => r.FornecedorId == fornecedorId).ToList();


                ViewBag.FornecedorId = fornecedorId;
                ViewBag.NomeFornecedor = _fornecedorService.GetById(fornecedorId).Result.Nome;

                IPagedList<EntregaMaterialDTO> allEntregasPaginadas = allEntregas.ToPagedList(pagina, 10);

                return View("ListaEntregas", allEntregasPaginadas);
            }

            ViewBag.xCondition = 1;

            ViewBag.FornecedorId = fornecedorId;

            ViewBag.NomeFornecedor = _fornecedorService.GetById(fornecedorId).Result.Nome;

            IPagedList<EntregaMaterialDTO> entregasPaginadas = xEntregas.ToPagedList();

            return View("ListaEntregas", entregasPaginadas);
        }

        // Página de pesquisa de entregas de materiais por data de inicio e data fim para relatório em PDF
        public IActionResult RelatorioEntregas(int id)
        {
            ViewBag.FornecedorId = id;
            return View();
        }

        // Gerar Relatorio de entregas em PDF
        public IActionResult RelatorioEntregasPDF(int id, DateTime dataInicio, DateTime dataFim)
        {
            // Tentar fazer chegar a data correta

            ViewData["DataInicio"] = dataInicio.ToShortDateString();
            ViewData["DataFim"] = dataFim.ToShortDateString();
            ViewData["NomeFornecedor"] = _fornecedorService.GetById(id).Result.Nome.ToString();

            var xEntregas = _entregaMaterialService.GetEntregasMateriais().Result.Where(x => x.FornecedorId == id).Where(x => x.Data >= dataInicio).Where(x => x.Data <= dataFim).ToList();

            var xFornecedorNome = _fornecedorService.GetById(id).Result.Nome;

            return new ViewAsPdf(xEntregas, viewData: ViewData)
            {
                IsGrayScale = false,
                PageSize = Rotativa.AspNetCore.Options.Size.A4,
                PageMargins = new Rotativa.AspNetCore.Options.Margins(0, 10, 0, 10),

            };
        }


        // Get retiradas fornecedor específico
        public async Task<IActionResult> ListaRetiradas(int? id, int pagina = 1)
        {
            var xRetiradas = await _retiradaMaterialService.GetRetiradasMateriais();
            var detalhes = xRetiradas.Where(x => x.FornecedorId == id);


            ViewBag.NomeFornecedor = _fornecedorService.GetById(id).Result.Nome;

            ViewBag.FornecedorId = id;

            IPagedList<RetiradaMaterialDTO> allRetiradas = detalhes.ToPagedList(pagina, 10);

            return View(allRetiradas);
        }


        // Campo de pesquisa para filtrar uma retirada por data específica
        [HttpPost]
        public ActionResult GetDataRetirada(DateTime data, int fornecedorId, int pagina = 1)
        {
            var xRetiradas = _retiradaMaterialService.GetRetiradasMateriais().Result.Where(r => r.Data == data).Where(r => r.FornecedorId == fornecedorId).ToList();

            if (xRetiradas.Count == 0)
            {
                TempData["error"] = "Data não localizada.";
                var allRetiradas = _retiradaMaterialService.GetRetiradasMateriais().Result.Where(r => r.FornecedorId == fornecedorId).ToList();


                ViewBag.FornecedorId = fornecedorId;
                ViewBag.NomeFornecedor = _fornecedorService.GetById(fornecedorId).Result.Nome;

                IPagedList<RetiradaMaterialDTO> allRetiradasPaginadas = allRetiradas.ToPagedList(pagina, 10);

                return View("ListaRetiradas", allRetiradasPaginadas);
            }

            ViewBag.xCondition = 1;

            ViewBag.FornecedorId = fornecedorId;

            ViewBag.NomeFornecedor = _fornecedorService.GetById(fornecedorId).Result.Nome;

            IPagedList<RetiradaMaterialDTO> retiradasPaginadas = xRetiradas.ToPagedList();

            return View("ListaRetiradas", retiradasPaginadas);
        }


        // Página de pesquisa de retirada de materiais por data de inicio e data fim para relatório em PDF
        public IActionResult RelatorioRetiradas(int id)
        {
            ViewBag.FornecedorId = id;
            return View();
        }

        // Gerar Relatorio de entregas em PDF
        public IActionResult RelatorioRetiradasPDF(int id, DateTime dataInicio, DateTime dataFim)
        {
            // Tentar fazer chegar a data correta

            ViewData["DataInicio"] = dataInicio.ToShortDateString();
            ViewData["DataFim"] = dataFim.ToShortDateString();
            ViewData["NomeFornecedor"] = _fornecedorService.GetById(id).Result.Nome.ToString();

            var xEntregas = _retiradaMaterialService.GetRetiradasMateriais().Result.Where(x => x.FornecedorId == id).Where(x => x.Data >= dataInicio).Where(x => x.Data <= dataFim).ToList();

            var xFornecedorNome = _fornecedorService.GetById(id).Result.Nome;

            return new ViewAsPdf(xEntregas, viewData: ViewData)
            {
                IsGrayScale = true,
                PageSize = Rotativa.AspNetCore.Options.Size.A4,
                PageMargins = new Rotativa.AspNetCore.Options.Margins(0, 10, 0, 10),

            };
        }




        // Add fornecedor
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(FornecedorDTO fornecedorDTO)
        {
            if (ModelState.IsValid)
            {
                await _fornecedorService.Add(fornecedorDTO);
                TempData["success"] = "Fornecedor Cadastrado com sucesso.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Erro ao cadastrar o fornecedor.";
            }

            return View();
        }

        // Edit fornecedor
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var xFornecedor = await _fornecedorService.GetById(id);

            if (xFornecedor == null)
                return NotFound();

            return View(xFornecedor);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(FornecedorDTO fornecedorDTO)
        {
            if (ModelState.IsValid)
            {
                await _fornecedorService.Update(fornecedorDTO);
                TempData["success"] = "Fornecedor editado com sucesso.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Erro ao editar o fornecedor.";
            }

            return View(fornecedorDTO);
        }

        // Remove fornecedor
        [HttpGet]
        public async Task<IActionResult> Remove(int? id)
        {
            if (id == null)
                TempData["error"] = "Erro ao localizar o fornecedor";

            var xFornecedor = await _fornecedorService.GetById(id);

            if (xFornecedor == null)
                TempData["error"] = "Erro ao localizar o fornecedor";

            return View(xFornecedor);
        }

        [HttpPost(), ActionName("Remove")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

Requisicao_RSS.WebUi/Controllers/RetiradaMateriaisController.cs
using Microsoft.AspNetCore.Mvc;
using Requisicao_RSS.Application.DTOs;
using Requisicao_RSS.Application.Interfaces;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Requisicao_RSS.WebUi.Controllers
{
    public class RetiradaMateriaisController : Controller
    {
        // Injeção de dependência
        private readonly IRetiradaMaterialService _retiradaMaterialService;
        private readonly IFornecedorService _fornecedorService;

        public RetiradaMateriaisController(IRetiradaMaterialService retiradaaMaterialService, IFornecedorService fornecedorService)
        {
            _retiradaMaterialService = retiradaaMaterialService;
            _fornecedorService = fornecedorService;
        }

        // GetAll retiradas de materiais
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var xRetiradas = await _retiradaMaterialService.GetRetiradasMateriais();


            return View(xRetiradas);
        }

        // Campo para filtrar uma retirada em uma data específica
        [HttpPost]
        public ActionResult GetDataRetiradas(DateTime data)
        {
            var xRetiradas = _retiradaMaterialService.GetRetiradasMateriais().Result.Where(r => r.Data == data).ToList();

            if (xRetiradas.Count == 0)
            {
                var AllRetiradas = _retiradaMaterialService.GetRetiradasMateriais();
                TempData["error"] = "Data não localizada.";
                
                return RedirectToAction("Index", AllRetiradas);
            }

            return View("Index", xRetiradas);
        }

        // Detalhes de uma retirada específica
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var xEntregas = await _retiradaMaterialService.GetById(id);


            return View(xEntregas);

        }


        // Add retirada de materiais
        [HttpGet]
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
                TempData["error"] = "Erro ao localizar a retirada.";

            // Localiza um fornecedor
            var xFornecedor = await _fornecedorService.GetById(id);

            // Captura informações do fornecedor 
            ViewBag.FornecedorId = xFornecedor.FornecedorId;
            ViewBag.FornecedorNome = xFornecedor.Nome;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RetiradaMaterialDTO retiradaMaterial)
        {            
            if (ModelState.IsValid)
            {
                await _retiradaMaterialService.Add(retiradaMaterial);
                TempData["success"] = "Retirada cadastrada com sucesso.";
                return RedirectToAction("Index", "Fornecedores");
            }
            else
            {
                TempData["error"] = "Erro ao cadastrar a retirada.";
            }

            // Manda novamente informações do fornecedor
            ViewBag.FornecedorNome = retiradaMaterial.NomeFornecedor;
            ViewBag.FornecedorId = retiradaMaterial.FornecedorId;

            return View(retiradaMaterial);

        }


        // Edit retirada de material
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                TempData["error"] = "Erro ao localizar a retirada.";
            }

            var xRetiradaMaterial = await _retiradaMaterialService.GetById(id);

            if (xRetiradaMaterial == null)
            {
                return NotFound();
            }

            return View(xRetiradaMaterial);
        }


        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> Edit(RetiradaMaterialDTO retiradaMaterial)
        {
            if (ModelState.IsValid)
            {
                await _retiradaMaterialService.Update(retiradaMaterial);
                TempData["success"] = "Retirada editada com sucesso.";
                return RedirectToAction("ListaRetiradas", "Fornecedores", new { @id = retiradaMaterial.FornecedorId });
            }
            else
            {
                TempData["error"] = "Erro ao editar a retirada.";
            }

            // Localiza o fornecedor
            var xFornecedor = await _fornecedorService.GetById(retiradaMaterial.FornecedorId);

            // Captura informações do fornecedor
            ViewBag.FornecedorNome = retiradaMaterial.NomeFornecedor;

            return View(retiradaMaterial);
        }


        // Remove retirada de material
        [HttpGet]
        public async Task<IActionResult> Remove(int? id)
        {
            if (id == null)
                TempData["error"] = "Erro ao localizar a retirada.";

            var xRetirada = await _retiradaMaterialService.GetById(id);

            if (xRetirada == null)
                TempData["error"] = "Erro ao localizar a retirada.";

            return View(xRetirada);
        }

        [HttpPost(), ActionName("Remove")]
        public async Task<IActionResult> DeleteConfirmed(int id, int fornecedorId)
        {
            await _retiradaMaterialService.Remove(id);

            var xFornecedorId = _fornecedorService.GetById(fornecedorId).Result.FornecedorId;

            TempData["success"] = "Retirada removida com sucesso.";
            return RedirectToAction("ListaRetiradas", "Fornecedores", new { @id = xFornecedorId });
        }
    }
}

Requisicao_RSS.WebUi/Views/Fornecedores/Create.cshtml
<!--Import model-->
@model Requisicao_RSS.Application.DTOs.FornecedorDTO
<!-- Header -->
<div class="row">
    <div class="col-12 text-center mt-3 mb-3">
        <h2 style="font-weight: 200">Cadastrar Fornecedor</h2>
    </div>
</div>

<!-- Formulário de cadastro de fornecedor -->
<form asp-action="Create" method="POST" style="width:70%; margin: 0 auto;">
    <hr />

    <!-- Exibe lista de erros de validações do formulário -->
    <div asp-validation-summary="All" class="text-danger"></div>


    <div class="form-group">
        <div class="row">
            <!-- Nome -->
            <div class="col-md-7">
                <label asp-for="Nome">Nome</label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <!-- Telefone -->
            <div class="col-md-5">
                <label asp-for="Telefone">Telefone</label>
                <input asp-for="Telefone" class="form-control" placeholder="(xx)xxxxx-xxxx" id="txtTelefone" />
            </div>
        </div>
    </div>

    <!-- Cnpj -->
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label asp-for="CNPJ">CNPJ</label>
                <input asp-for="CNPJ" class="form-control" id="txtCNPJ" />
            </div>
        </div>
    </div>

    <!-- Ações -->
    <div class="form-group">
        <div class="row">
            <div class="col-md-4 d-flex justify-content-start">
                <button type="submit" class="btn btn-primary d-flex btn-acoes btn-add">
                    <span class="mr-1">Cadastrar</span>
                    <i class="material-icons" style="font-size:15px;color:white;">add</i>
                </button>
                <div class="btn btn-danger d-flex btn-acoes ml-3">
                    <a style="color:#fff;" asp-action="Index"><span class="mr-1">Cancelar</span></a>
                    <i class="material-icons" style="font-size:15px;color:white;">clear</i>
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Scripts -->
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#txtTelefone').mask('(00)0000-0000');
            $('#txtCNPJ').mask('00.000.000/0000-00');
        });
    </script>
}

Requisicao_RSS.WebUi/Views/Fornecedores/Details.cshtml
<!-- Import model -->
@model Requisicao_RSS.Application.DTOs.FornecedorDTO
<!-- Header-->
<div class="row">
    <div class="col-12 mt-3 mb-3 text-center">
        <h2 style="font-weight: 200">Detalhes @Model.Nome</h2>
        <hr style="width:30%;" />
    </div>
</div>



<!-- Ações -->
<div class="container">
    <div class="row">
        <div class="col-3">
            <a asp-controller="EntregaMateriais" asp-action="Create" asp-route-id="@Model.FornecedorId" class="btn btn-primary d-flex justify-content-center">
                <span>Cadastrar Entrega</span>
            </a>
        </div>
        <div class="col-3">
            <a asp-controller="RetiradaMateriais" asp-action="Create" asp-route-id="@Model.FornecedorId" class="btn btn-primary d-flex justify-content-center">
                <span>Cadastrar Retirada</span>
            </a>
        </div>
        <div class="col-3">
            <a asp-action="ListaEntregas" asp-route-id="@Model.FornecedorId" class="btn btn-primary d-flex justify-content-center">
                <span>Lista de Entregas</span>
            </a>
        </div>
        <div class="col-3">
            <a asp-action="ListaRetiradas" asp-route-id="@Model.FornecedorId" class="btn btn-primary d-flex justify-content-center">
                <span>Lista de Retiradas</span>
            </a>
        </div>
    </div>

</div>

Requisicao_RSS.WebUi/Views/Fornecedores/Edit.cshtml
<!-- Import model-->
@model Requisicao_RSS.Application.DTOs.FornecedorDTO
<!-- Header-->
<div class="row">
    <div class="col-12 text-center mt-3 mb-3">
        <h2 style="font-weight: 200">Editar Fornecedor</h2>
    </div>
</div>

<!-- Formulário de edição de fornecedor -->
<form asp-action="Edit" method="POST" style="width:70%; margin: 0 auto;">
    <hr />

    <!-- Exibe lista de erros de validações do formulário -->
    <div asp-validation-summary="All" class="text-danger"></div>

    <!-- Id fornecedor -->
    <input type="hidden" asp-for="FornecedorId" value="@Model.FornecedorId" />

    <div class="form-group">
        <div class="row">
            <!-- Nome -->
            <div class="col-md-7">
                <label asp-for="Nome">Nome</label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <!-- Telefone -->
            <div class="col-md-5">
                <label asp-for="Telefone">Telefone</label>
                <input asp-for="Telefone" class="form-control" placeholder="(xx)xxxxx-xxxx" id="txtTelefone" />
            </div>
        </div>
    </div>

    <!-- Cnpj -->
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label asp-for="CNPJ">CNPJ</label>
                <input asp-for="CNPJ" class="form-control" id="txtCNPJ" />
            </div>
        </div>
    </div>

    <!-- Ações -->
    <div class="form-group">
        <div class="row">
            <div class="col-md-4 d-flex justify-content-start">
                <button type="submit" class="btn btn-primary d-flex btn-acoes btn-add">
                    <span class="mr-1">Editar</span>
                    <i class="material-icons" style="font-size:15px;color:white;">edit</i>
                </button>
                <div class="btn btn-danger d-flex btn-acoes ml-3">
                    <a style="color:#fff;" asp-action="Index"><span class="mr-1">Cancelar</span></a>
                    <i class="material-icons" style="font-size:15px;color:white;">clear</i>
                </div>
            </div>
        </div>
    </div>
</form>

Requisicao_RSS.WebUi/Views/Fornecedores/Index.cshtml
<!-- Import model-->
@model IEnumerable<Requisicao_RSS.Application.DTOs.FornecedorDTO>
<!-- Header-->
<div class="row">
    <div class="col-12 mt-3">
        <h2 style="font-weight: 200">Fornecedores</h2>
    </div>
</div>

<hr />

<!-- Btn cadastrar fornecedor -->
<div class="row">
    <div class="col-md-3 col-6">
        <a class="btn btn-primary d-flex align-items-center justify-content-center" asp-action="Create">
            <span class="mr-1">Cadastrar Fornecedor</span>
            <i class="material-icons p-r-3" style="font-size:20px;color:white;">add</i>
        </a>
    </div>
</div>

<!-- Lista de Fornecedores-->
<div class="row">
    <div class="col-12 mt-3">
        <div class="table-responsive">
            <table class="table table-bordered table-sm text-center">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>CNPJ</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                            <td>@Html.DisplayFor(modelItem => item.Telefone)</td>
                            <td>@Html.DisplayFor(modelItem => item.CNPJ)</td>

                            <!-- Ações -->
                            <td style="width:220px;">
                                <!-- Opções fornecedor -->
                                <a asp-action="Details" asp-route-id="@item.FornecedorId" class="btn btn-sm btn-info"  data-toggle="tooltip" data-placement="bottom" title="Lista de Opções">
                                    <i class="material-icons">feed</i>
                                </a>
                                <!-- Editar fornecedor -->
                                <a asp-action="Edit" asp-route-id="@item.FornecedorId" class="btn btn-sm btn-dark"  data-toggle="tooltip" data-placement="bottom" title="Editar Fornecedor">
                                    <i class="material-icons">edit</i>
                                </a>
                                <!-- Remover fornecedor -->
                                <a asp-action="Remove" asp-route-id="@item.FornecedorId" class="btn btn-sm btn-danger"  data-toggle="tooltip" data-placement="bottom" title="Remover Fornecedor">
                                    <i class="material-icons">delete</i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Requisicao_RSS.WebUi/Views/Fornecedores/ListaRetiradas.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Bootstrap4.Core
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

<!-- Model com os dados paginados -->
@model X.PagedList.PagedList<Requisicao_RSS.Application.DTOs.RetiradaMaterialDTO>
<!-- Header -->
<div class="row">
    <div class="col-12 mt-3 mb-3">
        <h4 style="font-weight: 200">Lista de saída de materiais &nbsp;-&nbsp; <strong>@ViewBag.NomeFornecedor</strong></h4>
    </div>
</div>
<div class="row">
    <div class="col-3 col-md-1">
        <a asp-controller="Fornecedores" asp-action="Details" asp-route-id="@ViewBag.FornecedorId" class="d-flex align-items-center justify-content-center btn btn-primary btn-sm"><i class="material-icons" style="font-size:15px;color:#fff;">arrow_back_ios</i>Voltar</a>
    </div>
</div>

<div class="row">
    <div class="col-3 mt-3">
        @using (Html.BeginForm("GetDataRetirada", "Fornecedores", FormMethod.Post))
        {

            <div class="row">
                <div class="col-10">
                    <input type="hidden" value="@ViewBag.FornecedorId" name="fornecedorId" id="fornecedorId" />
                    <input class="form-control" type="date" id="data" name="data">
                </div>
                <div class="col-2">
                    <input class="btn btn-primary" type="submit" value="Filtrar">
                </div>
            </div>
        }
    </div>
</div>

<hr />


<!-- Opções de paginação -->
@if (ViewBag.xCondition != 1)
{
    <div class="row">
        <div class="col-12">

            <span class="font-weight-light">Página @Model.PageNumber de @Model.PageCount</span>
            <div class="mt-2">
                @Html.PagedListPager(Model, pagina => Url.Action("ListaEntregas", new { pagina, id = ViewBag.FornecedorId }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded }.ApplyBootstrap4Style())
            </div>

        </div>
    </div>
}




<!-- Relatório em PDF -->
<div class="row">
    <div class="col ml-1">
        <a class="btn btn-info btn-sm" asp-action="RelatorioRetiradas" asp-route-id="@ViewBag.FornecedorId" data-toggle="tooltip" data-placement="bottom" title="Relatório em PDF">Gerar relatório</a>
    </div>
</div>



<!-- Informações de retiradas de um fornecedor específico -->
<table class="table table-bordered table-sm mt-3 text-center">
    <thead>
        <tr>

            <th>Data</th>
            <th>Nome</th>
            <th>Tipo</th>
            @if (Model.Any(c => c.Tipo == "Uniforme"))
            {
                <th>Quantidade Camisas</th>
                <th>Quantidade Calças</th>
            }
            @if (Model.Any(c => c.Tipo == "Luva"))
            {
                <th>Quantidade Luvas</th>
            }
            
            <th>Divergência</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Data)</td>
            <td>@ViewBag.NomeFornecedor</td>
            <td>@Html.DisplayFor(modelItem => item.Tipo)</td>
            @if (Model.Any(c => c.Tipo == "Uniforme"))
            {
                <td>@Html.DisplayFor(modelItem => item.QuantidadeCamisas)</td>
                <td>@Html.DisplayFor(modelItem => item.QuantidadeCalcas)</td>
            }
            @if (Model.Any(c => c.Tipo == "Luva"))
            {
                <td>@Html.DisplayFor(modelItem => item.QuantidadeLuvas)</td>
            }

            
           
                <td>@Html.DisplayFor(modelItem => item.Divergencia)</td>
          

            <!-- Ações -->
            <td style="width:220px;">
                <!-- Detalhes da entrega -->
                <a asp-controller="RetiradaMateriais" asp-action="Details" asp-route-id="@item.RetiradaMaterialId" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Detalhes Retirada">
                    <i class="material-icons">feed</i>
                </a>
                <!-- Editar entrega -->
                <a asp-controller="RetiradaMateriais" asp-action="Edit" asp-route-id="@item.RetiradaMaterialId" class="btn btn-sm btn-dark" data-toggle="tooltip" data-placement="top" title="Editar Retirada">
                    <i class="material-icons">edit</i>
                </a>
                <!-- Remover entrega -->
                <a asp-controller="RetiradaMateriais" asp-action="Remove" asp-route-id="@item.RetiradaMaterialId" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Remover Retirada">
                    <i class="material-icons">delete</i>
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>